[package]
name = "leptos_virtual_scroller"
version = "0.1.1"
edition = "2021"

[dependencies]
leptos = { version = "0.8.11", features = ["csr"] }
leptos-use = "0.16.3"
leptos_dom = "0.8.7"
wasm-bindgen = "0.2.104"

[workspace]
members = ["demo"]
