[package]
name = "leptos_virtual_scroller"
version = "0.1.1"
edition = "2021"

[dependencies]
leptos = { version = "0.7.3", features = ["csr"] }
leptos-use = "0.15.3"
leptos_dom = "0.7.3"

[workspace]
members = ["demo"]
