[package]
name = "leptos_virtual_scroller"
version = "0.1.1"
edition = "2021"

[dependencies]
leptos = { version = "0.6.14", features = ["csr"] }
leptos-use = "0.12.0"

[workspace]
members = ["demo"]
